# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anasayfa.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
class Ui_MainWindow(object):

    def Kullanici_Ekle(self):
        k_adi=self.k_adi_input.text()
        k_sifre=self.k_sifre_input.text()
        if k_adi=="" and k_sifre=="":
            self.hata('Kullanıcı Adı ve Şifre Hatası', 'Lütfen Kullanıcı Adı ve Şifre giriniz.')
        elif k_adi=="":
            self.hata('Kullanıcı Ad Hatası', 'Lütfen Kullanıcı Adı Giriniz.')
        elif k_sifre=="":
            self.hata('Kullanıcı Sifre Hatası','Lütfen Kullanıcı Sifre Giriniz.')
        else:
            k_durum="1"
            baglan=sqlite3.connect("veritabanı.db")
            kontrol=baglan.execute("INSERT INTO KULLANICILAR(K_ADI,K_SIFRE,K_DURUM) VALUES(?,?,?)", (k_adi, k_sifre, k_sifre))
            sorgu = kontrol.fetchall()
            if (sorgu):  # email adresi kayıtlı mı?
                self.hata('Başarılı!', 'Kullanıcı Kayıt Edildi...')
            else:
                self.hata('Hata!', 'Böyle Bir Kullanıcı Bulunmaktadır')



    def hata(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 593)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 140, 61, 21))
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 160, 361, 341))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.ip_duzenle_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ip_duzenle_btn.setGeometry(QtCore.QRect(10, 500, 101, 28))
        self.ip_duzenle_btn.setObjectName("ip_duzenle_btn")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(402, 11, 541, 81))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(420, 40, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(610, 40, 55, 16))
        self.label_3.setObjectName("label_3")
        self.baslat_ip_input = QtWidgets.QLineEdit(self.centralwidget)
        self.baslat_ip_input.setGeometry(QtCore.QRect(670, 31, 261, 31))
        self.baslat_ip_input.setObjectName("baslat_ip_input")
        self.baslat_btn = QtWidgets.QPushButton(self.centralwidget)
        self.baslat_btn.setGeometry(QtCore.QRect(570, 100, 93, 28))
        self.baslat_btn.setObjectName("baslat_btn")
        self.durdur_btn = QtWidgets.QPushButton(self.centralwidget)
        self.durdur_btn.setGeometry(QtCore.QRect(670, 100, 93, 28))
        self.durdur_btn.setObjectName("durdur_btn")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(12, 10, 351, 121))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 71, 20))
        self.label_5.setObjectName("label_5")
        self.ip_adres_ekle_input = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_adres_ekle_input.setGeometry(QtCore.QRect(100, 20, 251, 22))
        self.ip_adres_ekle_input.setObjectName("ip_adres_ekle_input")
        self.ip_adi_ekle_input = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_adi_ekle_input.setGeometry(QtCore.QRect(100, 60, 161, 22))
        self.ip_adi_ekle_input.setObjectName("ip_adi_ekle_input")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 60, 41, 16))
        self.label_6.setObjectName("label_6")
        self.ip_ekle_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ip_ekle_btn.setGeometry(QtCore.QRect(100, 90, 93, 28))
        self.ip_ekle_btn.setObjectName("ip_ekle_btn")
        self.baslat_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.baslat_comboBox.setGeometry(QtCore.QRect(470, 40, 111, 22))
        self.baslat_comboBox.setObjectName("baslat_comboBox")
        self.baslat_comboBox.addItem("")
        self.baslat_comboBox.addItem("")
        self.baslat_comboBox.addItem("")
        self.ip_sil_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ip_sil_btn.setGeometry(QtCore.QRect(110, 500, 91, 28))
        self.ip_sil_btn.setObjectName("ip_sil_btn")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(400, 160, 541, 401))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(430, 170, 121, 16))
        self.label_4.setObjectName("label_4")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(430, 190, 431, 181))
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 2, item)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(430, 430, 381, 121))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(450, 440, 71, 20))
        self.label_7.setObjectName("label_7")
        self.k_adi_input = QtWidgets.QLineEdit(self.centralwidget)
        self.k_adi_input.setGeometry(QtCore.QRect(540, 440, 171, 22))
        self.k_adi_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.k_adi_input.setObjectName("k_adi_input")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(450, 480, 81, 20))
        self.label_8.setObjectName("label_8")
        self.k_sifre_input = QtWidgets.QLineEdit(self.centralwidget)
        self.k_sifre_input.setGeometry(QtCore.QRect(540, 480, 171, 22))
        self.k_sifre_input.setObjectName("k_sifre_input")
        self.k_ekle_btn = QtWidgets.QPushButton(self.centralwidget)
        self.k_ekle_btn.setGeometry(QtCore.QRect(540, 510, 93, 28))
        self.k_ekle_btn.setObjectName("k_ekle_btn")
        #kullanıcı ekle butonuna tıklayınca
        self.k_ekle_btn.clicked.connect(self.Kullanici_Ekle)
        self.k_duzenle_btn = QtWidgets.QPushButton(self.centralwidget)
        self.k_duzenle_btn.setGeometry(QtCore.QRect(430, 370, 111, 28))
        self.k_duzenle_btn.setObjectName("k_duzenle_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Anasayfa"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>IP Listesi</p></body></html>"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "otopark"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "cadde"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.ip_duzenle_btn.setText(_translate("MainWindow", "Seçili IP Duzenle"))
        self.label_2.setText(_translate("MainWindow", "Admin"))
        self.label_3.setText(_translate("MainWindow", "IP Adres"))
        self.baslat_btn.setText(_translate("MainWindow", "Başlat"))
        self.durdur_btn.setText(_translate("MainWindow", "Durdur"))
        self.label_5.setText(_translate("MainWindow", "IP Adresi"))
        self.label_6.setText(_translate("MainWindow", "IP Adı"))
        self.ip_ekle_btn.setText(_translate("MainWindow", "IP Ekle"))
        self.baslat_comboBox.setItemText(0, _translate("MainWindow", "IP Seçili Değil"))
        self.baslat_comboBox.setItemText(1, _translate("MainWindow", "Engin"))
        self.baslat_comboBox.setItemText(2, _translate("MainWindow", "Demet"))
        self.ip_sil_btn.setText(_translate("MainWindow", "Seçili IP Sil"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Kullanıcı Listesi</span></p></body></html>"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Kullanıcı Adı"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Kullanıcı Şifre"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "Durumu"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_7.setText(_translate("MainWindow", "Kullanıcı Adı"))
        self.label_8.setText(_translate("MainWindow", "Kullanıcı Şifre"))
        self.k_ekle_btn.setText(_translate("MainWindow", "Kullanıcı Ekle"))
        self.k_duzenle_btn.setText(_translate("MainWindow", "Kullanıcı Düzenle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

